# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: generic
sudo: required
dist: trusty


os:
  - linux

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - LAZ_VER=1.8.2 LAZ_ENV=linux LAZ_OPT="--os=linux --cpu=x86_64"

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &
  - chmod +x ./ci/travis.install.py

before_install:
  - Xvfb $DISPLAY &
  # https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0.4/lazarus-project_2.0.4-0_amd64.deb/download
  - wget https://netcologne.dl.sourceforge.net/project/lazarus/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0.2/fpc-laz_3.0.4-1_amd64.deb
  - wget https://netcologne.dl.sourceforge.net/project/lazarus/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0.2/fpc-src_3.0.4-2_amd64.deb
  - wget https://netcologne.dl.sourceforge.net/project/lazarus/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0.2/lazarus-project_2.0.2-0_amd64.deb
install:
  - sudo apt-get install libgtk2.0-dev
  - sudo dpkg -i *.deb

script:
  - lazbuild pck/paxhttp_package.lpk 

notifications:
  email:
    on_success: false
    on_failure: change

